spring:
  datasource:
    url: jdbc:mysql:///mail?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  application:
    name: account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 9001

#pagehelper:
#  helper-dialect:on
#  reasonable:true
#  support-methods-arguments:true
#  pageSizeZero:true




# ??????
#logging:
#  level:
#    root: info
#    com.js.bookstore.service: debug
# 配置mybatis-plus
mybatis-plus:
  mapper-locations:
    classpath*:/com/mail/mailserver/dao/*.xml
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl